🌐 i18n on README
Vicente015/AnnounceIt pull request #6
Opened 2023-01-15 14:51 UTC by wiletki

This contribution adds a README.es-ES that is translated to Spanish.
The original README has got a link to switch to the Spanish file, in this one a link to switch to the original is added.

![imagen](https://user-images.githubusercontent.com/87622950/212548198-fa88c87c-23f6-48bd-ba55-46748d1f6042.png)
![imagen](https://user-images.githubusercontent.com/87622950/212548212-081179cb-8645-4511-abaf-4ebe595a9c76.png)

2023-01-17 20:40 UTC, Vicente015 requested changes
Thank you! Some words can be improved :)

2023-01-17 20:40 UTC, Vicente015 commented on README.es-ES.md
> +- Crear un anuncio usando los modals nativos de Discord.
```suggestion
- Crear un anuncio usando los formularios nativos de Discord.
```

2023-01-17 20:40 UTC, Vicente015 commented on README.es-ES.md
> +- Personalizar con imágenes, miniaturas, título y pie de página en el embed.
```suggestion
- Personalizar con imágenes, miniaturas, título y pie de página el embed.
```

2023-01-17 20:40 UTC, Vicente015 approved these changes
Everything fine! :)

2023-01-17 20:41 UTC, merged

2023-01-18 15:18 UTC, wiletki commented
Thank you!